---
apiVersion: v2
appVersion: 3.3.2
description: ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home
name: grocy
version: 0.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - grocy
home: https://github.com/towo/helm-charts/
icon: https://github.com/grocy/grocy/raw/master/public/img/appicons/mstile-150x150.png
sources:
  - https://github.com/grocy/grocy
  - https://github.com/grocy/grocy-docker
maintainers:
  - name: Tobias Wolter
