---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.frontendName" . }}
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP  }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    {{- if  .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/component: frontend
    {{- include "grocy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.backendName" . }}
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: fpm
    port: 9000
  selector:
    app.kubernetes.io/component: backend
    {{- include "grocy.selectorLabels" . | nindent 4 }}

